[package]
name = "figure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azusa = { version = "0.1.0", git = "https://github.com/Lattexshz/Azusa", features = ["window","png"]}
winit = "0.28.2"