[package]
name = "figure-dll"
version = "0.1.0"
edition = "2021"

[lib]
name = "figure"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
figure = { version = "0.1.0", path = "../figure" }